name: cartelera_peliculas
description: Una aplicación de cartelera de películas

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  dio: ^5.3.2
  cached_network_image: ^3.2.3
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1  # Asegúrate de que sea una versión completa